"""Initial migration1

Revision ID: dc83bffbf6a5
Revises: 
Create Date: 2025-03-07 21:23:27.712164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc83bffbf6a5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('name', sa.Text(length=255), nullable=True),
    sa.Column('color', sa.Text(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=True),
    sa.Column('grade', sa.JSON(), nullable=True),
    sa.Column('grade_min', sa.Integer(), nullable=True),
    sa.Column('grade_max', sa.Integer(), nullable=True),
    sa.Column('school_year', sa.Text(length=9), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_class_id'), 'class', ['id'], unique=False)
    op.create_index(op.f('ix_class_name'), 'class', ['name'], unique=False)
    op.create_table('class_subject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(length=255), nullable=True),
    sa.Column('color', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_class_subject_id'), 'class_subject', ['id'], unique=False)
    op.create_index(op.f('ix_class_subject_name'), 'class_subject', ['name'], unique=False)
    op.create_table('subject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(length=255), nullable=True),
    sa.Column('color', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subject_id'), 'subject', ['id'], unique=False)
    op.create_index(op.f('ix_subject_name'), 'subject', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subject_name'), table_name='subject')
    op.drop_index(op.f('ix_subject_id'), table_name='subject')
    op.drop_table('subject')
    op.drop_index(op.f('ix_class_subject_name'), table_name='class_subject')
    op.drop_index(op.f('ix_class_subject_id'), table_name='class_subject')
    op.drop_table('class_subject')
    op.drop_index(op.f('ix_class_name'), table_name='class')
    op.drop_index(op.f('ix_class_id'), table_name='class')
    op.drop_table('class')
    # ### end Alembic commands ###
