"""Change to Prep/Class Prep

Revision ID: 0bb168245247
Revises: 1b4dbda0892f
Create Date: 2025-05-01 19:26:14.279791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0bb168245247'
down_revision: Union[str, None] = '1b4dbda0892f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prep',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('color', sa.Text(length=10), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('grade_level', sa.Text(length=255), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prep_id'), 'prep', ['id'], unique=False)
    op.create_table('prep_concept',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=True),
    sa.Column('prep_id', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['concept_id'], ['concept.id'], ),
    sa.ForeignKeyConstraint(['prep_id'], ['prep.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prep_concept_id'), 'prep_concept', ['id'], unique=False)
    op.drop_index('ix_shared_concept_id', table_name='shared_concept')
    op.drop_table('shared_concept')
    op.drop_index('ix_shared_subject_id', table_name='shared_subject')
    op.drop_table('shared_subject')
    op.alter_column('class', 'color',
               existing_type=mysql.TINYTEXT(),
               type_=sa.Text(length=10),
               existing_nullable=True)
    op.alter_column('class', 'grade_level',
               existing_type=mysql.TINYTEXT(),
               type_=sa.Text(length=2),
               existing_nullable=True)
    op.alter_column('class', 'school_year',
               existing_type=mysql.TINYTEXT(),
               type_=sa.Text(length=9),
               existing_nullable=True)
    op.alter_column('class_subject', 'color',
               existing_type=mysql.TINYTEXT(),
               type_=sa.Text(length=10),
               existing_nullable=True)
    op.alter_column('group_meeting', 'time',
               existing_type=mysql.TINYTEXT(),
               type_=sa.Text(length=5),
               existing_nullable=True)
    op.alter_column('group_meeting', 'minutes',
               existing_type=mysql.TINYTEXT(),
               type_=sa.Text(length=2),
               existing_nullable=True)
    op.add_column('metric', sa.Column('prep_concept_id', sa.Integer(), nullable=True))
    op.alter_column('metric', 'level_scale',
               existing_type=mysql.TEXT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_constraint('metric_ibfk_1', 'metric', type_='foreignkey')
    op.create_foreign_key(None, 'metric', 'prep_concept', ['prep_concept_id'], ['id'])
    op.drop_column('metric', 'concept_id')
    op.alter_column('school', 'color',
               existing_type=mysql.TINYTEXT(),
               type_=sa.Text(length=10),
               existing_nullable=True)
    op.alter_column('standard', 'grade_level',
               existing_type=mysql.TINYTEXT(),
               type_=sa.Text(length=50),
               existing_nullable=True)
    op.alter_column('student_class', 'color',
               existing_type=mysql.TINYTEXT(),
               type_=sa.Text(length=10),
               existing_nullable=True)
    op.alter_column('student_note', 'color',
               existing_type=mysql.TINYTEXT(),
               type_=sa.Text(length=10),
               existing_nullable=True)
    op.alter_column('team', 'color',
               existing_type=mysql.TINYTEXT(),
               type_=sa.Text(length=10),
               existing_nullable=True)
    op.alter_column('unit', 'color',
               existing_type=mysql.TINYTEXT(),
               type_=sa.Text(length=10),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('unit', 'color',
               existing_type=sa.Text(length=10),
               type_=mysql.TINYTEXT(),
               existing_nullable=True)
    op.alter_column('team', 'color',
               existing_type=sa.Text(length=10),
               type_=mysql.TINYTEXT(),
               existing_nullable=True)
    op.alter_column('student_note', 'color',
               existing_type=sa.Text(length=10),
               type_=mysql.TINYTEXT(),
               existing_nullable=True)
    op.alter_column('student_class', 'color',
               existing_type=sa.Text(length=10),
               type_=mysql.TINYTEXT(),
               existing_nullable=True)
    op.alter_column('standard', 'grade_level',
               existing_type=sa.Text(length=50),
               type_=mysql.TINYTEXT(),
               existing_nullable=True)
    op.alter_column('school', 'color',
               existing_type=sa.Text(length=10),
               type_=mysql.TINYTEXT(),
               existing_nullable=True)
    op.add_column('metric', sa.Column('concept_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'metric', type_='foreignkey')
    op.create_foreign_key('metric_ibfk_1', 'metric', 'concept', ['concept_id'], ['id'])
    op.alter_column('metric', 'level_scale',
               existing_type=sa.Integer(),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.drop_column('metric', 'prep_concept_id')
    op.alter_column('group_meeting', 'minutes',
               existing_type=sa.Text(length=2),
               type_=mysql.TINYTEXT(),
               existing_nullable=True)
    op.alter_column('group_meeting', 'time',
               existing_type=sa.Text(length=5),
               type_=mysql.TINYTEXT(),
               existing_nullable=True)
    op.alter_column('class_subject', 'color',
               existing_type=sa.Text(length=10),
               type_=mysql.TINYTEXT(),
               existing_nullable=True)
    op.alter_column('class', 'school_year',
               existing_type=sa.Text(length=9),
               type_=mysql.TINYTEXT(),
               existing_nullable=True)
    op.alter_column('class', 'grade_level',
               existing_type=sa.Text(length=2),
               type_=mysql.TINYTEXT(),
               existing_nullable=True)
    op.alter_column('class', 'color',
               existing_type=sa.Text(length=10),
               type_=mysql.TINYTEXT(),
               existing_nullable=True)
    op.create_table('shared_subject',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('color', mysql.TINYTEXT(), nullable=True),
    sa.Column('subject_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('grade_level', mysql.TEXT(), nullable=True),
    sa.Column('teacher_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], name='shared_subject_ibfk_1'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], name='shared_subject_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_shared_subject_id', 'shared_subject', ['id'], unique=False)
    op.create_table('shared_concept',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('concept_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('shared_subject_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['concept_id'], ['concept.id'], name='shared_concept_ibfk_2'),
    sa.ForeignKeyConstraint(['shared_subject_id'], ['shared_subject.id'], name='shared_concept_ibfk_3'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_shared_concept_id', 'shared_concept', ['id'], unique=False)
    op.drop_index(op.f('ix_prep_concept_id'), table_name='prep_concept')
    op.drop_table('prep_concept')
    op.drop_index(op.f('ix_prep_id'), table_name='prep')
    op.drop_table('prep')
    # ### end Alembic commands ###
