"""Add teacher model and rename users to user

Revision ID: 1253e20833cd
Revises: aea865587636
Create Date: 2025-03-22 08:19:17.533421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1253e20833cd'
down_revision: Union[str, None] = 'aea865587636'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('user',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('type', sa.Text(length=255), nullable=True),
    # sa.Column('name', sa.Text(length=255), nullable=True),
    # sa.Column('img', sa.Text(length=255), nullable=True),
    # sa.Column('email', sa.Text(length=255), nullable=True),
    # sa.Column('password', sa.Text(length=255), nullable=True),
    # sa.Column('premium', sa.Boolean(), nullable=True),
    # sa.Column('school', sa.Integer(), nullable=True),
    # sa.Column('bday_notification_day', sa.Text(length=255), nullable=True),
    # sa.Column('bday_notification_time', sa.Text(length=255), nullable=True),
    # sa.ForeignKeyConstraint(['school'], ['school.id'], ),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    # op.drop_index('ix_users_id', table_name='users')
    # op.drop_table('users')
    # op.drop_constraint('assign_ibfk_1', 'assign', type_='foreignkey')
    op.create_foreign_key(None, 'assign', 'teacher', ['teacher_id'], ['id'])
    # op.add_column('class', sa.Column('teacher_id', sa.Integer(), nullable=True))
    op.alter_column('class', 'color',
               existing_type=mysql.TINYTEXT(),
               type_=sa.Text(length=10),
               existing_nullable=True)
    op.alter_column('class', 'school_year',
               existing_type=mysql.TINYTEXT(),
               type_=sa.Text(length=9),
               existing_nullable=True)
    # op.drop_constraint('class_ibfk_1', 'class', type_='foreignkey')
    op.create_foreign_key(None, 'class', 'teacher', ['teacher_id'], ['id'])
    # op.drop_column('class', 'user_id')
    op.alter_column('class_subject', 'color',
               existing_type=mysql.TINYTEXT(),
               type_=sa.Text(length=10),
               existing_nullable=True)
    op.alter_column('group_meeting', 'time',
               existing_type=mysql.TINYTEXT(),
               type_=sa.Text(length=5),
               existing_nullable=True)
    op.alter_column('group_meeting', 'minutes',
               existing_type=mysql.TINYTEXT(),
               type_=sa.Text(length=2),
               existing_nullable=True)
    # op.drop_constraint('layout_ibfk_1', 'layout', type_='foreignkey')
    op.create_foreign_key(None, 'layout', 'teacher', ['teacher_id'], ['id'])
    # op.drop_constraint('metric_ibfk_2', 'metric', type_='foreignkey')
    op.create_foreign_key(None, 'metric', 'teacher', ['teacher_id'], ['id'])
    op.alter_column('school', 'color',
               existing_type=mysql.TINYTEXT(),
               type_=sa.Text(length=10),
               existing_nullable=True)
    op.alter_column('standard', 'grade',
               existing_type=mysql.TINYTEXT(),
               type_=sa.Text(length=50),
               existing_nullable=True)
    op.alter_column('student_class', 'color',
               existing_type=mysql.TINYTEXT(),
               type_=sa.Text(length=10),
               existing_nullable=True)
    op.alter_column('student_note', 'color',
               existing_type=mysql.TINYTEXT(),
               type_=sa.Text(length=10),
               existing_nullable=True)
    op.alter_column('subject', 'color',
               existing_type=mysql.TINYTEXT(),
               type_=sa.Text(length=10),
               existing_nullable=True)
    # op.drop_constraint('teacher_ibfk_1', 'teacher', type_='foreignkey')
    op.create_foreign_key(None, 'teacher', 'user', ['user_id'], ['id'])
    op.alter_column('team', 'color',
               existing_type=mysql.TINYTEXT(),
               type_=sa.Text(length=10),
               existing_nullable=True)
    # op.drop_constraint('team_ibfk_2', 'team', type_='foreignkey')
    op.drop_column('team', 'team_admin_id')
    op.add_column('unit', sa.Column('teacher_id', sa.Integer(), nullable=True))
    op.alter_column('unit', 'color',
               existing_type=mysql.TINYTEXT(),
               type_=sa.Text(length=10),
               existing_nullable=True)
    # op.drop_constraint('unit_ibfk_1', 'unit', type_='foreignkey')
    # op.drop_constraint('unit_ibfk_3', 'unit', type_='foreignkey')
    op.create_foreign_key(None, 'unit', 'teacher', ['teacher_id'], ['id'])
    op.drop_column('unit', 'user_id')
    op.drop_column('unit', 'created_by')
    # op.drop_constraint('user_team_ibfk_2', 'user_team', type_='foreignkey')
    # op.drop_constraint('user_team_ibfk_2', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'user_team', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'user_team', type_='foreignkey')
    op.create_foreign_key('user_team_ibfk_2', 'user_team', 'users', ['user_id'], ['id'])
    op.add_column('unit', sa.Column('created_by', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('unit', sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    # op.drop_constraint(None, 'unit', type_='foreignkey')
    op.create_foreign_key('unit_ibfk_3', 'unit', 'users', ['user_id'], ['id'])
    op.create_foreign_key('unit_ibfk_1', 'unit', 'users', ['created_by'], ['id'])
    op.alter_column('unit', 'color',
               existing_type=sa.Text(length=10),
               type_=mysql.TINYTEXT(),
               existing_nullable=True)
    op.drop_column('unit', 'teacher_id')
    op.add_column('team', sa.Column('team_admin_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('team_ibfk_2', 'team', 'users', ['team_admin_id'], ['id'])
    op.alter_column('team', 'color',
               existing_type=sa.Text(length=10),
               type_=mysql.TINYTEXT(),
               existing_nullable=True)
    # op.drop_constraint(None, 'teacher', type_='foreignkey')
    op.create_foreign_key('teacher_ibfk_1', 'teacher', 'users', ['user_id'], ['id'])
    op.alter_column('subject', 'color',
               existing_type=sa.Text(length=10),
               type_=mysql.TINYTEXT(),
               existing_nullable=True)
    op.alter_column('student_note', 'color',
               existing_type=sa.Text(length=10),
               type_=mysql.TINYTEXT(),
               existing_nullable=True)
    op.alter_column('student_class', 'color',
               existing_type=sa.Text(length=10),
               type_=mysql.TINYTEXT(),
               existing_nullable=True)
    op.alter_column('standard', 'grade',
               existing_type=sa.Text(length=50),
               type_=mysql.TINYTEXT(),
               existing_nullable=True)
    op.alter_column('school', 'color',
               existing_type=sa.Text(length=10),
               type_=mysql.TINYTEXT(),
               existing_nullable=True)
    # op.drop_constraint(None, 'metric', type_='foreignkey')
    op.create_foreign_key('metric_ibfk_2', 'metric', 'users', ['teacher_id'], ['id'])
    # op.drop_constraint(None, 'layout', type_='foreignkey')
    op.create_foreign_key('layout_ibfk_1', 'layout', 'users', ['teacher_id'], ['id'])
    op.alter_column('group_meeting', 'minutes',
               existing_type=sa.Text(length=2),
               type_=mysql.TINYTEXT(),
               existing_nullable=True)
    op.alter_column('group_meeting', 'time',
               existing_type=sa.Text(length=5),
               type_=mysql.TINYTEXT(),
               existing_nullable=True)
    op.alter_column('class_subject', 'color',
               existing_type=sa.Text(length=10),
               type_=mysql.TINYTEXT(),
               existing_nullable=True)
    op.add_column('class', sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    # op.drop_constraint(None, 'class', type_='foreignkey')
    op.create_foreign_key('class_ibfk_1', 'class', 'users', ['user_id'], ['id'])
    op.alter_column('class', 'school_year',
               existing_type=sa.Text(length=9),
               type_=mysql.TINYTEXT(),
               existing_nullable=True)
    op.alter_column('class', 'color',
               existing_type=sa.Text(length=10),
               type_=mysql.TINYTEXT(),
               existing_nullable=True)
    op.drop_column('class', 'teacher_id')
    # op.drop_constraint(None, 'assign', type_='foreignkey')
    op.create_foreign_key('assign_ibfk_1', 'assign', 'users', ['teacher_id'], ['id'])
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('type', mysql.TEXT(), nullable=True),
    sa.Column('name', mysql.TEXT(), nullable=True),
    sa.Column('img', mysql.TEXT(), nullable=True),
    sa.Column('email', mysql.TEXT(), nullable=True),
    sa.Column('password', mysql.TEXT(), nullable=True),
    sa.Column('premium', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('school', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('bday_notification_day', mysql.TEXT(), nullable=True),
    sa.Column('bday_notification_time', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['school'], ['school.id'], name='users_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
