"""Updating structure

Revision ID: 14a8c0f44e35
Revises: 1b318ed0d524
Create Date: 2025-03-18 22:28:18.152366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '14a8c0f44e35'
down_revision: Union[str, None] = '1b318ed0d524'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_subject_id', table_name='subject')
    op.drop_table('subject')
    op.drop_index('ix_class_subject_id', table_name='class_subject')
    op.drop_table('class_subject')
    op.drop_index('ix_class_id', table_name='class')
    op.drop_table('class')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', mysql.TEXT(), nullable=True),
    sa.Column('color', mysql.TINYTEXT(), nullable=True),
    sa.Column('archived', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('grade', mysql.JSON(), nullable=True),
    sa.Column('grade_min', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('grade_max', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('school_year', mysql.TINYTEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_class_id', 'class', ['id'], unique=False)
    op.create_table('class_subject',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('color', mysql.TINYTEXT(), nullable=True),
    sa.Column('name', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_class_subject_id', 'class_subject', ['id'], unique=False)
    op.create_table('subject',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.TEXT(), nullable=True),
    sa.Column('color', mysql.TINYTEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_subject_id', 'subject', ['id'], unique=False)
    # ### end Alembic commands ###
