"""Initial migration2

Revision ID: 1b318ed0d524
Revises: fd295cf055c7
Create Date: 2025-03-07 21:53:33.697350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1b318ed0d524'
down_revision: Union[str, None] = 'fd295cf055c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('name', sa.Text(length=255), nullable=True),
    sa.Column('color', sa.Text(length=10), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=True),
    sa.Column('grade', sa.JSON(), nullable=True),
    sa.Column('grade_min', sa.Integer(), nullable=True),
    sa.Column('grade_max', sa.Integer(), nullable=True),
    sa.Column('school_year', sa.Text(length=9), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_class_id'), 'class', ['id'], unique=False)
    op.create_table('subject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(length=255), nullable=True),
    sa.Column('color', sa.Text(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subject_id'), 'subject', ['id'], unique=False)
    op.add_column('class_subject', sa.Column('name', sa.Text(length=255), nullable=True))
    op.alter_column('class_subject', 'color',
               existing_type=mysql.TINYTEXT(),
               type_=sa.Text(length=10),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('class_subject', 'color',
               existing_type=sa.Text(length=10),
               type_=mysql.TINYTEXT(),
               existing_nullable=True)
    op.drop_column('class_subject', 'name')
    op.drop_index(op.f('ix_subject_id'), table_name='subject')
    op.drop_table('subject')
    op.drop_index(op.f('ix_class_id'), table_name='class')
    op.drop_table('class')
    # ### end Alembic commands ###
