"""Add student_concept_metric & history

Revision ID: 1c7c1f9431c5
Revises: 6ba184228d12
Create Date: 2025-05-21 21:01:58.827669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1c7c1f9431c5'
down_revision: Union[str, None] = '6ba184228d12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_concept_metric',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('concept_id', sa.Integer(), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(length=1000), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], ),
    sa.ForeignKeyConstraint(['concept_id'], ['prep_concept.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_concept_metric_id'), 'student_concept_metric', ['id'], unique=False)
    op.create_table('student_concept_metric_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_concept_metric_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(length=1000), nullable=True),
    sa.Column('old_level', sa.Integer(), nullable=True),
    sa.Column('new_level', sa.Integer(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_concept_metric_id'], ['student_concept_metric.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_concept_metric_history_id'), 'student_concept_metric_history', ['id'], unique=False)
    op.alter_column('class', 'color',
               existing_type=mysql.TINYTEXT(),
               type_=sa.Text(length=10),
               existing_nullable=True)
    op.alter_column('class', 'grade_level',
               existing_type=mysql.TINYTEXT(),
               type_=sa.Text(length=2),
               existing_nullable=True)
    op.alter_column('class', 'school_year',
               existing_type=mysql.TINYTEXT(),
               type_=sa.Text(length=9),
               existing_nullable=True)
    op.alter_column('class_subject', 'color',
               existing_type=mysql.TINYTEXT(),
               type_=sa.Text(length=10),
               existing_nullable=True)
    op.alter_column('group_meeting', 'time',
               existing_type=mysql.TINYTEXT(),
               type_=sa.Text(length=5),
               existing_nullable=True)
    op.alter_column('group_meeting', 'minutes',
               existing_type=mysql.TINYTEXT(),
               type_=sa.Text(length=2),
               existing_nullable=True)
    op.alter_column('prep', 'color',
               existing_type=mysql.TINYTEXT(),
               type_=sa.Text(length=10),
               existing_nullable=True)
    op.alter_column('school', 'color',
               existing_type=mysql.TINYTEXT(),
               type_=sa.Text(length=10),
               existing_nullable=True)
    op.alter_column('standard', 'grade_level',
               existing_type=mysql.TINYTEXT(),
               type_=sa.Text(length=50),
               existing_nullable=True)
    op.alter_column('student_class', 'color',
               existing_type=mysql.TINYTEXT(),
               type_=sa.Text(length=10),
               existing_nullable=True)
    op.add_column('student_metric', sa.Column('class_metric_id', sa.Integer(), nullable=True))
    op.add_column('student_metric', sa.Column('notes', sa.Text(length=1000), nullable=True))
    op.drop_constraint('student_metric_ibfk_1', 'student_metric', type_='foreignkey')
    op.create_foreign_key(None, 'student_metric', 'class_metric', ['class_metric_id'], ['id'])
    op.drop_column('student_metric', 'note')
    op.drop_column('student_metric', 'metric_id')
    op.alter_column('student_note', 'color',
               existing_type=mysql.TINYTEXT(),
               type_=sa.Text(length=10),
               existing_nullable=True)
    op.alter_column('team', 'color',
               existing_type=mysql.TINYTEXT(),
               type_=sa.Text(length=10),
               existing_nullable=True)
    op.alter_column('unit', 'color',
               existing_type=mysql.TINYTEXT(),
               type_=sa.Text(length=10),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('unit', 'color',
               existing_type=sa.Text(length=10),
               type_=mysql.TINYTEXT(),
               existing_nullable=True)
    op.alter_column('team', 'color',
               existing_type=sa.Text(length=10),
               type_=mysql.TINYTEXT(),
               existing_nullable=True)
    op.alter_column('student_note', 'color',
               existing_type=sa.Text(length=10),
               type_=mysql.TINYTEXT(),
               existing_nullable=True)
    op.add_column('student_metric', sa.Column('metric_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('student_metric', sa.Column('note', mysql.TEXT(), nullable=True))
    op.drop_constraint(None, 'student_metric', type_='foreignkey')
    op.create_foreign_key('student_metric_ibfk_1', 'student_metric', 'metric', ['metric_id'], ['id'])
    op.drop_column('student_metric', 'notes')
    op.drop_column('student_metric', 'class_metric_id')
    op.alter_column('student_class', 'color',
               existing_type=sa.Text(length=10),
               type_=mysql.TINYTEXT(),
               existing_nullable=True)
    op.alter_column('standard', 'grade_level',
               existing_type=sa.Text(length=50),
               type_=mysql.TINYTEXT(),
               existing_nullable=True)
    op.alter_column('school', 'color',
               existing_type=sa.Text(length=10),
               type_=mysql.TINYTEXT(),
               existing_nullable=True)
    op.alter_column('prep', 'color',
               existing_type=sa.Text(length=10),
               type_=mysql.TINYTEXT(),
               existing_nullable=True)
    op.alter_column('group_meeting', 'minutes',
               existing_type=sa.Text(length=2),
               type_=mysql.TINYTEXT(),
               existing_nullable=True)
    op.alter_column('group_meeting', 'time',
               existing_type=sa.Text(length=5),
               type_=mysql.TINYTEXT(),
               existing_nullable=True)
    op.alter_column('class_subject', 'color',
               existing_type=sa.Text(length=10),
               type_=mysql.TINYTEXT(),
               existing_nullable=True)
    op.alter_column('class', 'school_year',
               existing_type=sa.Text(length=9),
               type_=mysql.TINYTEXT(),
               existing_nullable=True)
    op.alter_column('class', 'grade_level',
               existing_type=sa.Text(length=2),
               type_=mysql.TINYTEXT(),
               existing_nullable=True)
    op.alter_column('class', 'color',
               existing_type=sa.Text(length=10),
               type_=mysql.TINYTEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_student_concept_metric_history_id'), table_name='student_concept_metric_history')
    op.drop_table('student_concept_metric_history')
    op.drop_index(op.f('ix_student_concept_metric_id'), table_name='student_concept_metric')
    op.drop_table('student_concept_metric')
    # ### end Alembic commands ###
