"""Add analytics to user model + update properties

Revision ID: 5b361a9b9f89
Revises: f02259a8fcee
Create Date: 2025-07-28 06:42:33.108372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5b361a9b9f89'
down_revision: Union[str, None] = 'f02259a8fcee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('class', sa.Column('created_at', sa.DateTime(), nullable=True))
    # op.alter_column('class', 'color',
    #            existing_type=mysql.TINYTEXT(),
    #            type_=sa.Text(length=10),
    #            existing_nullable=True)
    # op.alter_column('class', 'grade_level',
    #            existing_type=mysql.TINYTEXT(),
    #            type_=sa.Text(length=2),
    #            existing_nullable=True)
    # op.alter_column('class', 'school_year',
    #            existing_type=mysql.TINYTEXT(),
    #            type_=sa.Text(length=9),
    #            existing_nullable=True)
    # op.add_column('class_note', sa.Column('created_at', sa.DateTime(), nullable=True))
    # op.add_column('class_note', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # op.drop_column('class_note', 'created')
    # op.drop_column('class_note', 'updated')
    # op.alter_column('class_subject', 'color',
    #            existing_type=mysql.TINYTEXT(),
    #            type_=sa.Text(length=10),
    #            existing_nullable=True)
    # op.alter_column('group_meeting', 'time',
    #            existing_type=mysql.TINYTEXT(),
    #            type_=sa.Text(length=5),
    #            existing_nullable=True)
    # op.alter_column('group_meeting', 'minutes',
    #            existing_type=mysql.TINYTEXT(),
    #            type_=sa.Text(length=2),
    #            existing_nullable=True)
    # op.alter_column('prep', 'color',
    #            existing_type=mysql.TINYTEXT(),
    #            type_=sa.Text(length=10),
    #            existing_nullable=True)
    # op.add_column('prep_concept', sa.Column('created_at', sa.DateTime(), nullable=True))
    # op.alter_column('school', 'color',
    #            existing_type=mysql.TINYTEXT(),
    #            type_=sa.Text(length=10),
    #            existing_nullable=True)
    # op.alter_column('standard', 'grade_level',
    #            existing_type=mysql.TINYTEXT(),
    #            type_=sa.Text(length=50),
    #            existing_nullable=True)
    # op.alter_column('student', 'gender',
    #            existing_type=mysql.TINYTEXT(),
    #            type_=sa.Text(length=1),
    #            existing_nullable=True)
    # op.alter_column('student_class', 'color',
    #            existing_type=mysql.TINYTEXT(),
    #            type_=sa.Text(length=10),
    #            existing_nullable=True)
    # op.alter_column('student_note', 'color',
    #            existing_type=mysql.TINYTEXT(),
    #            type_=sa.Text(length=10),
    #            existing_nullable=True)
    # op.alter_column('team', 'color',
    #            existing_type=mysql.TINYTEXT(),
    #            type_=sa.Text(length=10),
    #            existing_nullable=True)
    # op.alter_column('unit', 'color',
    #            existing_type=mysql.TINYTEXT(),
    #            type_=sa.Text(length=10),
    #            existing_nullable=True)
    # op.add_column('user', sa.Column('school_id', sa.Integer(), nullable=True))
    # op.add_column('user', sa.Column('signup_date', sa.DateTime(), nullable=True))
    # op.add_column('user', sa.Column('last_login', sa.DateTime(), nullable=True))
    # op.add_column('user', sa.Column('login_count', sa.Integer(), nullable=True))
    op.alter_column('user', 'email',
               existing_type=sa.Text(length=255),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.create_unique_constraint(None, 'user', ['email'])
    op.drop_constraint('user_ibfk_1', 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'school', ['school_id'], ['id'])
    op.drop_column('user', 'school')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('school', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key('user_ibfk_1', 'user', 'school', ['school'], ['id'])
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'login_count')
    op.drop_column('user', 'last_login')
    op.drop_column('user', 'signup_date')
    op.drop_column('user', 'school_id')
    # op.alter_column('user', 'email',
    #            existing_type=sa.String(length=255),
    #            type_=sa.Text(length=255),
    #            existing_nullable=False)
    op.alter_column('unit', 'color',
               existing_type=sa.Text(length=10),
               type_=mysql.TINYTEXT(),
               existing_nullable=True)
    op.alter_column('team', 'color',
               existing_type=sa.Text(length=10),
               type_=mysql.TINYTEXT(),
               existing_nullable=True)
    op.alter_column('student_note', 'color',
               existing_type=sa.Text(length=10),
               type_=mysql.TINYTEXT(),
               existing_nullable=True)
    op.alter_column('student_class', 'color',
               existing_type=sa.Text(length=10),
               type_=mysql.TINYTEXT(),
               existing_nullable=True)
    op.alter_column('student', 'gender',
               existing_type=sa.Text(length=1),
               type_=mysql.TINYTEXT(),
               existing_nullable=True)
    op.alter_column('standard', 'grade_level',
               existing_type=sa.Text(length=50),
               type_=mysql.TINYTEXT(),
               existing_nullable=True)
    op.alter_column('school', 'color',
               existing_type=sa.Text(length=10),
               type_=mysql.TINYTEXT(),
               existing_nullable=True)
    op.drop_column('prep_concept', 'created_at')
    op.alter_column('prep', 'color',
               existing_type=sa.Text(length=10),
               type_=mysql.TINYTEXT(),
               existing_nullable=True)
    op.alter_column('group_meeting', 'minutes',
               existing_type=sa.Text(length=2),
               type_=mysql.TINYTEXT(),
               existing_nullable=True)
    op.alter_column('group_meeting', 'time',
               existing_type=sa.Text(length=5),
               type_=mysql.TINYTEXT(),
               existing_nullable=True)
    op.alter_column('class_subject', 'color',
               existing_type=sa.Text(length=10),
               type_=mysql.TINYTEXT(),
               existing_nullable=True)
    op.add_column('class_note', sa.Column('updated', mysql.DATETIME(), nullable=True))
    op.add_column('class_note', sa.Column('created', mysql.DATETIME(), nullable=True))
    op.drop_column('class_note', 'updated_at')
    op.drop_column('class_note', 'created_at')
    op.alter_column('class', 'school_year',
               existing_type=sa.Text(length=9),
               type_=mysql.TINYTEXT(),
               existing_nullable=True)
    op.alter_column('class', 'grade_level',
               existing_type=sa.Text(length=2),
               type_=mysql.TINYTEXT(),
               existing_nullable=True)
    op.alter_column('class', 'color',
               existing_type=sa.Text(length=10),
               type_=mysql.TINYTEXT(),
               existing_nullable=True)
    op.drop_column('class', 'created_at')
    # ### end Alembic commands ###
