"""Initial migration2

Revision ID: 831fab5273eb
Revises: 
Create Date: 2025-03-07 21:52:06.559654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '831fab5273eb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('class_subject', 'name')
    op.drop_column('class_subject', 'color')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class_subject', sa.Column('color', mysql.TEXT(), nullable=True))
    op.add_column('class_subject', sa.Column('name', mysql.TEXT(), nullable=True))
    # ### end Alembic commands ###
