"""Initial migration

Revision ID: cb8c4af47f7b
Revises: 
Create Date: 2025-03-05 19:56:36.591213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb8c4af47f7b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dream_signs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('color', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dream_signs_id'), 'dream_signs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dream_signs_id'), table_name='dream_signs')
    op.drop_table('dream_signs')
    # ### end Alembic commands ###
