"""Update Student Model - Add gender/school ids

Revision ID: f02259a8fcee
Revises: 5146cfe493f6
Create Date: 2025-07-27 08:37:09.408170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f02259a8fcee'
down_revision: Union[str, None] = '5146cfe493f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('class', 'color',
               existing_type=mysql.TINYTEXT(),
               type_=sa.Text(length=10),
               existing_nullable=True)
    op.alter_column('class', 'grade_level',
               existing_type=mysql.TINYTEXT(),
               type_=sa.Text(length=2),
               existing_nullable=True)
    op.alter_column('class', 'school_year',
               existing_type=mysql.TINYTEXT(),
               type_=sa.Text(length=9),
               existing_nullable=True)
    op.alter_column('class_subject', 'color',
               existing_type=mysql.TINYTEXT(),
               type_=sa.Text(length=10),
               existing_nullable=True)
    op.alter_column('group_meeting', 'time',
               existing_type=mysql.TINYTEXT(),
               type_=sa.Text(length=5),
               existing_nullable=True)
    op.alter_column('group_meeting', 'minutes',
               existing_type=mysql.TINYTEXT(),
               type_=sa.Text(length=2),
               existing_nullable=True)
    op.alter_column('prep', 'color',
               existing_type=mysql.TINYTEXT(),
               type_=sa.Text(length=10),
               existing_nullable=True)
    op.create_foreign_key(None, 'prep', 'teacher', ['teacher_id'], ['id'])
    op.alter_column('school', 'color',
               existing_type=mysql.TINYTEXT(),
               type_=sa.Text(length=10),
               existing_nullable=True)
    op.alter_column('standard', 'grade_level',
               existing_type=mysql.TINYTEXT(),
               type_=sa.Text(length=50),
               existing_nullable=True)
    op.add_column('student', sa.Column('school_student_id', sa.Text(length=255), nullable=True))
    op.add_column('student', sa.Column('school_id', sa.Integer(), nullable=True))
    op.add_column('student', sa.Column('gender', sa.Text(length=1), nullable=True))
    op.create_foreign_key(None, 'student', 'school', ['school_id'], ['id'])
    op.alter_column('student_class', 'color',
               existing_type=mysql.TINYTEXT(),
               type_=sa.Text(length=10),
               existing_nullable=True)
    op.alter_column('student_note', 'color',
               existing_type=mysql.TINYTEXT(),
               type_=sa.Text(length=10),
               existing_nullable=True)
    op.alter_column('team', 'color',
               existing_type=mysql.TINYTEXT(),
               type_=sa.Text(length=10),
               existing_nullable=True)
    op.alter_column('unit', 'color',
               existing_type=mysql.TINYTEXT(),
               type_=sa.Text(length=10),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('unit', 'color',
               existing_type=sa.Text(length=10),
               type_=mysql.TINYTEXT(),
               existing_nullable=True)
    op.alter_column('team', 'color',
               existing_type=sa.Text(length=10),
               type_=mysql.TINYTEXT(),
               existing_nullable=True)
    op.alter_column('student_note', 'color',
               existing_type=sa.Text(length=10),
               type_=mysql.TINYTEXT(),
               existing_nullable=True)
    op.alter_column('student_class', 'color',
               existing_type=sa.Text(length=10),
               type_=mysql.TINYTEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'student', type_='foreignkey')
    op.drop_column('student', 'gender')
    op.drop_column('student', 'school_id')
    op.drop_column('student', 'school_student_id')
    op.alter_column('standard', 'grade_level',
               existing_type=sa.Text(length=50),
               type_=mysql.TINYTEXT(),
               existing_nullable=True)
    op.alter_column('school', 'color',
               existing_type=sa.Text(length=10),
               type_=mysql.TINYTEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'prep', type_='foreignkey')
    op.alter_column('prep', 'color',
               existing_type=sa.Text(length=10),
               type_=mysql.TINYTEXT(),
               existing_nullable=True)
    op.alter_column('group_meeting', 'minutes',
               existing_type=sa.Text(length=2),
               type_=mysql.TINYTEXT(),
               existing_nullable=True)
    op.alter_column('group_meeting', 'time',
               existing_type=sa.Text(length=5),
               type_=mysql.TINYTEXT(),
               existing_nullable=True)
    op.alter_column('class_subject', 'color',
               existing_type=sa.Text(length=10),
               type_=mysql.TINYTEXT(),
               existing_nullable=True)
    op.alter_column('class', 'school_year',
               existing_type=sa.Text(length=9),
               type_=mysql.TINYTEXT(),
               existing_nullable=True)
    op.alter_column('class', 'grade_level',
               existing_type=sa.Text(length=2),
               type_=mysql.TINYTEXT(),
               existing_nullable=True)
    op.alter_column('class', 'color',
               existing_type=sa.Text(length=10),
               type_=mysql.TINYTEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
