"""Update concept / subject / metric tables

Revision ID: 2c747e61df37
Revises: 9de918123dd3
Create Date: 2025-04-01 21:01:32.990805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2c747e61df37'
down_revision: Union[str, None] = '9de918123dd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('class', 'color',
               existing_type=mysql.TINYTEXT(),
               type_=sa.Text(length=10),
               existing_nullable=True)
    op.alter_column('class', 'school_year',
               existing_type=mysql.TINYTEXT(),
               type_=sa.Text(length=9),
               existing_nullable=True)
    op.add_column('class_subject', sa.Column('class_id', sa.Integer(), nullable=True))
    op.add_column('class_subject', sa.Column('subject_id', sa.Integer(), nullable=True))
    op.alter_column('class_subject', 'color',
               existing_type=mysql.TINYTEXT(),
               type_=sa.Text(length=10),
               existing_nullable=True)
    op.create_index(op.f('ix_class_subject_class_id'), 'class_subject', ['class_id'], unique=False)
    op.create_index(op.f('ix_class_subject_subject_id'), 'class_subject', ['subject_id'], unique=False)
    op.drop_column('class_subject', 'name')
    op.add_column('concept', sa.Column('subject_id', sa.Integer(), nullable=True))
    op.add_column('concept', sa.Column('is_main_concept', sa.Boolean(), nullable=True))
    op.add_column('concept', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('concept', sa.Column('is_global', sa.Boolean(), nullable=True))
    op.add_column('concept', sa.Column('grade_level', sa.Text(length=255), nullable=True))
    op.create_foreign_key(None, 'concept', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'concept', 'subject', ['subject_id'], ['id'])
    op.alter_column('group_meeting', 'time',
               existing_type=mysql.TINYTEXT(),
               type_=sa.Text(length=5),
               existing_nullable=True)
    op.alter_column('group_meeting', 'minutes',
               existing_type=mysql.TINYTEXT(),
               type_=sa.Text(length=2),
               existing_nullable=True)
    op.drop_column('metric', 'date')
    op.alter_column('school', 'color',
               existing_type=mysql.TINYTEXT(),
               type_=sa.Text(length=10),
               existing_nullable=True)
    op.add_column('standard', sa.Column('domain', sa.Text(length=255), nullable=True))
    op.add_column('standard', sa.Column('subDomain', sa.Text(length=255), nullable=True))
    op.alter_column('standard', 'grade',
               existing_type=mysql.TINYTEXT(),
               type_=sa.Text(length=50),
               existing_nullable=True)
    op.alter_column('student_class', 'color',
               existing_type=mysql.TINYTEXT(),
               type_=sa.Text(length=10),
               existing_nullable=True)
    op.alter_column('student_note', 'color',
               existing_type=mysql.TINYTEXT(),
               type_=sa.Text(length=10),
               existing_nullable=True)
    op.add_column('subject', sa.Column('is_global', sa.Boolean(), nullable=True))
    op.add_column('subject', sa.Column('user_id', sa.Integer(), nullable=True))
    op.alter_column('subject', 'color',
               existing_type=mysql.TINYTEXT(),
               type_=sa.Text(length=10),
               existing_nullable=True)
    op.create_index(op.f('ix_subject_user_id'), 'subject', ['user_id'], unique=False)
    op.add_column('teacher', sa.Column('settings', postgresql.JSONB(astext_type=Text()), nullable=True))
    op.alter_column('team', 'color',
               existing_type=mysql.TINYTEXT(),
               type_=sa.Text(length=10),
               existing_nullable=True)
    op.alter_column('unit', 'color',
               existing_type=mysql.TINYTEXT(),
               type_=sa.Text(length=10),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('unit', 'color',
               existing_type=sa.Text(length=10),
               type_=mysql.TINYTEXT(),
               existing_nullable=True)
    op.alter_column('team', 'color',
               existing_type=sa.Text(length=10),
               type_=mysql.TINYTEXT(),
               existing_nullable=True)
    op.drop_column('teacher', 'settings')
    op.drop_index(op.f('ix_subject_user_id'), table_name='subject')
    op.alter_column('subject', 'color',
               existing_type=sa.Text(length=10),
               type_=mysql.TINYTEXT(),
               existing_nullable=True)
    op.drop_column('subject', 'user_id')
    op.drop_column('subject', 'is_global')
    op.alter_column('student_note', 'color',
               existing_type=sa.Text(length=10),
               type_=mysql.TINYTEXT(),
               existing_nullable=True)
    op.alter_column('student_class', 'color',
               existing_type=sa.Text(length=10),
               type_=mysql.TINYTEXT(),
               existing_nullable=True)
    op.alter_column('standard', 'grade',
               existing_type=sa.Text(length=50),
               type_=mysql.TINYTEXT(),
               existing_nullable=True)
    op.drop_column('standard', 'subDomain')
    op.drop_column('standard', 'domain')
    op.alter_column('school', 'color',
               existing_type=sa.Text(length=10),
               type_=mysql.TINYTEXT(),
               existing_nullable=True)
    op.add_column('metric', sa.Column('date', mysql.TEXT(), nullable=True))
    op.alter_column('group_meeting', 'minutes',
               existing_type=sa.Text(length=2),
               type_=mysql.TINYTEXT(),
               existing_nullable=True)
    op.alter_column('group_meeting', 'time',
               existing_type=sa.Text(length=5),
               type_=mysql.TINYTEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'concept', type_='foreignkey')
    op.drop_constraint(None, 'concept', type_='foreignkey')
    op.drop_column('concept', 'grade_level')
    op.drop_column('concept', 'is_global')
    op.drop_column('concept', 'user_id')
    op.drop_column('concept', 'is_main_concept')
    op.drop_column('concept', 'subject_id')
    op.add_column('class_subject', sa.Column('name', mysql.TEXT(), nullable=True))
    op.drop_index(op.f('ix_class_subject_subject_id'), table_name='class_subject')
    op.drop_index(op.f('ix_class_subject_class_id'), table_name='class_subject')
    op.alter_column('class_subject', 'color',
               existing_type=sa.Text(length=10),
               type_=mysql.TINYTEXT(),
               existing_nullable=True)
    op.drop_column('class_subject', 'subject_id')
    op.drop_column('class_subject', 'class_id')
    op.alter_column('class', 'school_year',
               existing_type=sa.Text(length=9),
               type_=mysql.TINYTEXT(),
               existing_nullable=True)
    op.alter_column('class', 'color',
               existing_type=sa.Text(length=10),
               type_=mysql.TINYTEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
