from sqlalchemy import Column, Integer, Text, ForeignKey, Boolean, Enum
from ..base import Base

class SeatingChart(Base):
  __tablename__ = "seating_chart"
  id = Column(Integer, primary_key=True, index=True)
  name = Column(Text(255))
  class_id = ForeignKey('class.id')
  created_at = Column(Text(255))
  layout_id = ForeignKey('layout.id')
  autogenerated_status = Column(Enum('none', 'partial', 'full', name='autogen_enum'), default='none') # partial if use auto then manually adjust, full if use auto then no manual adjustment
  status = Column(Enum('active', 'inactive', 'archived', name='chart_status_enum'), default='inactive')

