from sqlmodel import SQLModel, Field
from typing import Optional
from enum import Enum as PyEnum

class AutogenStatus(str, PyEnum):
    none = "none"
    partial = "partial"
    full = "full"

class ChartStatus(str, PyEnum):
    active = "active"
    inactive = "inactive"
    archived = "archived"

class SeatingChart(SQLModel, table=True):
    __tablename__ = "seating_chart"

    id: Optional[int] = Field(default=None, primary_key=True, index=True)
    name: str
    class_id: int = Field(foreign_key="class.id")
    created_at: Optional[str] = Field(default=None)
    layout_id: int = Field(foreign_key="layout.id")
    autogenerated_status: AutogenStatus = Field(default=AutogenStatus.none)
    status: ChartStatus = Field(default=ChartStatus.inactive)
    


