from sqlalchemy import Column, Integer, Text, ForeignKey, Enum, DateTime, func
from sqlalchemy.orm import relationship
from _models.base import Base
from sqlalchemy.ext.hybrid import hybrid_property

class SeatingChart(Base):
  __tablename__ = "seating_chart"
  id = Column(Integer, primary_key=True, index=True)
  name = Column(Text(255))
  created_at = Column(DateTime, default=func.now())
  status = Column(Enum('active', 'inactive', 'archived', name='chart_status_enum'), default='inactive')
  layout_id = Column(ForeignKey("layout.id"))
  class_id = Column(ForeignKey("class.id"))
  autogenerated_status = Column(Enum('none', 'partial', 'full', name='autogen_status_enum'), default='none')

  desks = relationship("StudentDesk")
  class_ = relationship('ClassModel')